# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LidarPlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LidarPlot(object):
    def setupUi(self, LidarPlot):
        LidarPlot.setObjectName("LidarPlot")
        LidarPlot.resize(546, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(LidarPlot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.export_button = QtWidgets.QPushButton(LidarPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_button.sizePolicy().hasHeightForWidth())
        self.export_button.setSizePolicy(sizePolicy)
        self.export_button.setObjectName("export_button")
        self.gridLayout.addWidget(self.export_button, 3, 2, 1, 1)
        self.widget = PlotWidget(LidarPlot)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 3)
        self.clear_button = QtWidgets.QPushButton(LidarPlot)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout.addWidget(self.clear_button, 3, 1, 1, 1)
        self.pause_button = QtWidgets.QPushButton(LidarPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_button.sizePolicy().hasHeightForWidth())
        self.pause_button.setSizePolicy(sizePolicy)
        self.pause_button.setObjectName("pause_button")
        self.gridLayout.addWidget(self.pause_button, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(LidarPlot)
        QtCore.QMetaObject.connectSlotsByName(LidarPlot)

    def retranslateUi(self, LidarPlot):
        _translate = QtCore.QCoreApplication.translate
        LidarPlot.setWindowTitle(_translate("LidarPlot", "Form"))
        self.export_button.setText(_translate("LidarPlot", "Export"))
        self.clear_button.setText(_translate("LidarPlot", "Clear"))
        self.pause_button.setText(_translate("LidarPlot", "Pause"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LidarPlot = QtWidgets.QWidget()
    ui = Ui_LidarPlot()
    ui.setupUi(LidarPlot)
    LidarPlot.show()
    sys.exit(app.exec_())
