# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TcpControl.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TcpControl(object):
    def setupUi(self, TcpControl):
        TcpControl.setObjectName("TcpControl")
        TcpControl.resize(450, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TcpControl)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        
        self.address_lineedit_label = QtWidgets.QLabel(TcpControl)
        self.address_lineedit_label.setObjectName("address_lineedit_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.address_lineedit_label)
        
        self.address_lineedit = QtWidgets.QLineEdit(TcpControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address_lineedit.sizePolicy().hasHeightForWidth())
        self.address_lineedit.setSizePolicy(sizePolicy)
        self.address_lineedit.setObjectName("address_lineedit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.address_lineedit)
        
        self.port_lineeidt_label = QtWidgets.QLabel(TcpControl)
        self.port_lineeidt_label.setObjectName("port_lineeidt_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.port_lineeidt_label)
        
        self.port_lineedit = QtWidgets.QLineEdit(TcpControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_lineedit.sizePolicy().hasHeightForWidth())
        self.port_lineedit.setSizePolicy(sizePolicy)
        self.port_lineedit.setObjectName("port_lineedit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.port_lineedit)
        self.verticalLayout_2.addLayout(self.formLayout)
        
        self.dis_conn_button = QtWidgets.QPushButton(TcpControl)
        self.dis_conn_button.setObjectName("dis_conn_button")
        self.verticalLayout_2.addWidget(self.dis_conn_button)
        
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        
        self.send_led = LedIndicator(TcpControl)
        self.send_led.setEnabled(False)
        self.send_led.setObjectName("send_led")
        self.verticalLayout.addWidget(self.send_led)
        
        self.send_led_label = QtWidgets.QLabel(TcpControl)
        self.send_led_label.setAlignment(QtCore.Qt.AlignCenter)
        self.send_led_label.setObjectName("send_led_label")
        self.verticalLayout.addWidget(self.send_led_label)
        
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        
        self.receive_led = LedIndicator(TcpControl)
        self.receive_led.setEnabled(False)
        self.receive_led.setObjectName("receive_led")
        self.verticalLayout.addWidget(self.receive_led)
        
        self.receive_led_label = QtWidgets.QLabel(TcpControl)
        self.receive_led_label.setAlignment(QtCore.Qt.AlignCenter)
        self.receive_led_label.setWordWrap(False)
        self.receive_led_label.setObjectName("receive_led_label")
        self.verticalLayout.addWidget(self.receive_led_label)
        
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(TcpControl)
        QtCore.QMetaObject.connectSlotsByName(TcpControl)

    def retranslateUi(self, TcpControl):
        _translate = QtCore.QCoreApplication.translate
        TcpControl.setWindowTitle(_translate("TcpControl", "Form"))
        self.address_lineedit_label.setText(_translate("TcpControl", "Server Address"))
        self.port_lineeidt_label.setText(_translate("TcpControl", "Server Port"))
        self.dis_conn_button.setText(_translate("TcpControl", "CONNECT"))
        self.send_led.setText(_translate("TcpControl", "PushButton"))
        self.send_led_label.setText(_translate("TcpControl", "TX"))
        self.receive_led.setText(_translate("TcpControl", "PushButton"))
        self.receive_led_label.setText(_translate("TcpControl", "RX"))
from LedIndicatorWidget import LedIndicator


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TcpControl = QtWidgets.QWidget()
    ui = Ui_TcpControl()
    ui.setupUi(TcpControl)
    TcpControl.show()
    sys.exit(app.exec_())
